DROP DATABASE IF EXISTS VIDEOHUB;
CREATE DATABASE VIDEOHUB;
USE VIDEOHUB;

CREATE TABLE VIDEO (
	ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
	TITLE VARCHAR(10),
	DESCRIPTION VARCHAR(20),
	PUBLICATION_DATE DATE
);

COMMIT;